ngl-test anim.py anim_forward_api refs/anim_forward_api.ref 
ngl-test anim.py anim_forward_float refs/anim_forward_float.ref 
ngl-test anim.py anim_forward_vec2 refs/anim_forward_vec2.ref 
ngl-test anim.py anim_forward_vec3 refs/anim_forward_vec3.ref 
ngl-test anim.py anim_forward_vec4 refs/anim_forward_vec4.ref 
ngl-test anim.py anim_forward_quat refs/anim_forward_quat.ref 
ngl-test anim.py anim_resolution_api refs/anim_resolution_api.ref 
ngl-test blending.py blending_all_diamond refs/blending_all_diamond.ref 
ngl-test blending.py blending_all_timed_diamond refs/blending_all_timed_diamond.ref 
ngl-test blending.py blending_none refs/blending_none.ref 
ngl-test blending.py blending_multiply refs/blending_multiply.ref 
ngl-test blending.py blending_screen refs/blending_screen.ref 
ngl-test blending.py blending_darken refs/blending_darken.ref 
ngl-test blending.py blending_lighten refs/blending_lighten.ref 
ngl-test compute.py compute_animation refs/compute_animation.ref 
ngl-test compute.py compute_histogram refs/compute_histogram.ref 
ngl-test compute.py compute_particules refs/compute_particules.ref 
ngl-test data.py data_single_float_uniform refs/data_single_float_uniform.ref 
ngl-test data.py data_single_int_uniform refs/data_single_int_uniform.ref 
ngl-test data.py data_single_mat4_uniform refs/data_single_mat4_uniform.ref 
ngl-test data.py data_single_quat_mat4_uniform refs/data_single_quat_mat4_uniform.ref 
ngl-test data.py data_single_quat_vec4_uniform refs/data_single_quat_vec4_uniform.ref 
ngl-test data.py data_single_vec2_uniform refs/data_single_vec2_uniform.ref 
ngl-test data.py data_single_vec3_uniform refs/data_single_vec3_uniform.ref 
ngl-test data.py data_single_vec4_uniform refs/data_single_vec4_uniform.ref 
ngl-test data.py data_animated_quat_mat4_uniform refs/data_animated_quat_mat4_uniform.ref 
ngl-test data.py data_animated_quat_vec4_uniform refs/data_animated_quat_vec4_uniform.ref 
ngl-test data.py data_array_float_uniform refs/data_array_float_uniform.ref 
ngl-test data.py data_array_vec2_uniform refs/data_array_vec2_uniform.ref 
ngl-test data.py data_array_vec3_uniform refs/data_array_vec3_uniform.ref 
ngl-test data.py data_array_vec4_uniform refs/data_array_vec4_uniform.ref 
ngl-test data.py data_single_float_std140 refs/data_single_float_std140.ref 
ngl-test data.py data_single_int_std140 refs/data_single_int_std140.ref 
ngl-test data.py data_single_mat4_std140 refs/data_single_mat4_std140.ref 
ngl-test data.py data_single_quat_mat4_std140 refs/data_single_quat_mat4_std140.ref 
ngl-test data.py data_single_quat_vec4_std140 refs/data_single_quat_vec4_std140.ref 
ngl-test data.py data_single_vec2_std140 refs/data_single_vec2_std140.ref 
ngl-test data.py data_single_vec3_std140 refs/data_single_vec3_std140.ref 
ngl-test data.py data_single_vec4_std140 refs/data_single_vec4_std140.ref 
ngl-test data.py data_animated_quat_mat4_std140 refs/data_animated_quat_mat4_std140.ref 
ngl-test data.py data_animated_quat_vec4_std140 refs/data_animated_quat_vec4_std140.ref 
ngl-test data.py data_array_float_std140 refs/data_array_float_std140.ref 
ngl-test data.py data_array_vec2_std140 refs/data_array_vec2_std140.ref 
ngl-test data.py data_array_vec3_std140 refs/data_array_vec3_std140.ref 
ngl-test data.py data_array_vec4_std140 refs/data_array_vec4_std140.ref 
ngl-test data.py data_animated_buffer_float_std140 refs/data_animated_buffer_float_std140.ref 
ngl-test data.py data_animated_buffer_vec2_std140 refs/data_animated_buffer_vec2_std140.ref 
ngl-test data.py data_animated_buffer_vec3_std140 refs/data_animated_buffer_vec3_std140.ref 
ngl-test data.py data_animated_buffer_vec4_std140 refs/data_animated_buffer_vec4_std140.ref 
ngl-test data.py data_array_int_std140 refs/data_array_int_std140.ref 
ngl-test data.py data_array_ivec2_std140 refs/data_array_ivec2_std140.ref 
ngl-test data.py data_array_ivec3_std140 refs/data_array_ivec3_std140.ref 
ngl-test data.py data_array_ivec4_std140 refs/data_array_ivec4_std140.ref 
ngl-test data.py data_array_mat4_std140 refs/data_array_mat4_std140.ref 
ngl-test data.py data_single_float_std430 refs/data_single_float_std430.ref 
ngl-test data.py data_single_int_std430 refs/data_single_int_std430.ref 
ngl-test data.py data_single_mat4_std430 refs/data_single_mat4_std430.ref 
ngl-test data.py data_single_quat_mat4_std430 refs/data_single_quat_mat4_std430.ref 
ngl-test data.py data_single_quat_vec4_std430 refs/data_single_quat_vec4_std430.ref 
ngl-test data.py data_single_vec2_std430 refs/data_single_vec2_std430.ref 
ngl-test data.py data_single_vec3_std430 refs/data_single_vec3_std430.ref 
ngl-test data.py data_single_vec4_std430 refs/data_single_vec4_std430.ref 
ngl-test data.py data_animated_quat_mat4_std430 refs/data_animated_quat_mat4_std430.ref 
ngl-test data.py data_animated_quat_vec4_std430 refs/data_animated_quat_vec4_std430.ref 
ngl-test data.py data_array_float_std430 refs/data_array_float_std430.ref 
ngl-test data.py data_array_vec2_std430 refs/data_array_vec2_std430.ref 
ngl-test data.py data_array_vec3_std430 refs/data_array_vec3_std430.ref 
ngl-test data.py data_array_vec4_std430 refs/data_array_vec4_std430.ref 
ngl-test data.py data_animated_buffer_float_std430 refs/data_animated_buffer_float_std430.ref 
ngl-test data.py data_animated_buffer_vec2_std430 refs/data_animated_buffer_vec2_std430.ref 
ngl-test data.py data_animated_buffer_vec3_std430 refs/data_animated_buffer_vec3_std430.ref 
ngl-test data.py data_animated_buffer_vec4_std430 refs/data_animated_buffer_vec4_std430.ref 
ngl-test data.py data_array_int_std430 refs/data_array_int_std430.ref 
ngl-test data.py data_array_ivec2_std430 refs/data_array_ivec2_std430.ref 
ngl-test data.py data_array_ivec3_std430 refs/data_array_ivec3_std430.ref 
ngl-test data.py data_array_ivec4_std430 refs/data_array_ivec4_std430.ref 
ngl-test data.py data_array_mat4_std430 refs/data_array_mat4_std430.ref 
ngl-test data.py data_streamed_buffer_vec4 refs/data_streamed_buffer_vec4.ref 
ngl-test data.py data_streamed_buffer_vec4_time_anim refs/data_streamed_buffer_vec4_time_anim.ref 
ngl-test live.py live_single_float_uniform refs/live_single_float_uniform.ref 
ngl-test live.py live_single_int_uniform refs/live_single_int_uniform.ref 
ngl-test live.py live_single_mat4_uniform refs/live_single_mat4_uniform.ref 
ngl-test live.py live_single_quat_mat4_uniform refs/live_single_quat_mat4_uniform.ref 
ngl-test live.py live_single_quat_vec4_uniform refs/live_single_quat_vec4_uniform.ref 
ngl-test live.py live_single_vec2_uniform refs/live_single_vec2_uniform.ref 
ngl-test live.py live_single_vec3_uniform refs/live_single_vec3_uniform.ref 
ngl-test live.py live_single_vec4_uniform refs/live_single_vec4_uniform.ref 
ngl-test live.py live_trf_single_mat4_uniform refs/live_trf_single_mat4_uniform.ref 
ngl-test live.py live_single_float_std140 refs/live_single_float_std140.ref 
ngl-test live.py live_single_int_std140 refs/live_single_int_std140.ref 
ngl-test live.py live_single_mat4_std140 refs/live_single_mat4_std140.ref 
ngl-test live.py live_single_quat_mat4_std140 refs/live_single_quat_mat4_std140.ref 
ngl-test live.py live_single_quat_vec4_std140 refs/live_single_quat_vec4_std140.ref 
ngl-test live.py live_single_vec2_std140 refs/live_single_vec2_std140.ref 
ngl-test live.py live_single_vec3_std140 refs/live_single_vec3_std140.ref 
ngl-test live.py live_single_vec4_std140 refs/live_single_vec4_std140.ref 
ngl-test live.py live_trf_single_mat4_std140 refs/live_trf_single_mat4_std140.ref 
ngl-test live.py live_single_float_std430 refs/live_single_float_std430.ref 
ngl-test live.py live_single_int_std430 refs/live_single_int_std430.ref 
ngl-test live.py live_single_mat4_std430 refs/live_single_mat4_std430.ref 
ngl-test live.py live_single_quat_mat4_std430 refs/live_single_quat_mat4_std430.ref 
ngl-test live.py live_single_quat_vec4_std430 refs/live_single_quat_vec4_std430.ref 
ngl-test live.py live_single_vec2_std430 refs/live_single_vec2_std430.ref 
ngl-test live.py live_single_vec3_std430 refs/live_single_vec3_std430.ref 
ngl-test live.py live_single_vec4_std430 refs/live_single_vec4_std430.ref 
ngl-test live.py live_trf_single_mat4_std430 refs/live_trf_single_mat4_std430.ref 
ngl-test media.py media_phases_display refs/media_phases_display.ref 
ngl-test media.py media_phases_resources refs/media_phases_resources.ref 
ngl-test rtt.py rtt_feature_depth refs/rtt_feature_depth.ref 
ngl-test rtt.py rtt_feature_depth_stencil refs/rtt_feature_depth_stencil.ref 
ngl-test rtt.py rtt_mipmap refs/rtt_mipmap.ref 
ngl-test rtt.py rtt_texture_depth_d16_unorm refs/rtt_texture_depth_d16_unorm.ref 
ngl-test rtt.py rtt_texture_depth_d24_unorm refs/rtt_texture_depth_d24_unorm.ref 
ngl-test rtt.py rtt_texture_depth_d24_unorm_s8_uint refs/rtt_texture_depth_d24_unorm_s8_uint.ref 
ngl-test rtt.py rtt_feature_depth_msaa refs/rtt_feature_depth_msaa.ref 
ngl-test rtt.py rtt_feature_depth_stencil_msaa refs/rtt_feature_depth_stencil_msaa.ref 
ngl-test rtt.py rtt_texture_depth_d16_unorm_msaa refs/rtt_texture_depth_d16_unorm_msaa.ref 
ngl-test rtt.py rtt_texture_depth_d24_unorm_msaa refs/rtt_texture_depth_d24_unorm_msaa.ref 
ngl-test rtt.py rtt_texture_depth_d24_unorm_s8_uint_msaa refs/rtt_texture_depth_d24_unorm_s8_uint_msaa.ref 
ngl-test shape.py shape_triangle refs/shape_triangle.ref 
ngl-test shape.py shape_triangles_mat4_attribute refs/shape_triangles_mat4_attribute.ref 
ngl-test shape.py shape_quad refs/shape_quad.ref 
ngl-test shape.py shape_circle refs/shape_circle.ref 
ngl-test shape.py shape_diamond_colormask refs/shape_diamond_colormask.ref 
ngl-test shape.py shape_geometry refs/shape_geometry.ref 
ngl-test shape.py shape_geometry_normals refs/shape_geometry_normals.ref 
ngl-test shape.py shape_geometry_indices refs/shape_geometry_indices.ref 
ngl-test shape.py shape_geometry_normals_indices refs/shape_geometry_normals_indices.ref 
ngl-test shape.py shape_geometry_rtt refs/shape_geometry_rtt.ref 
ngl-test shape.py shape_geometry_rtt_depth refs/shape_geometry_rtt_depth.ref 
ngl-test shape.py shape_morphing refs/shape_morphing.ref 
ngl-test shape.py shape_cropboard refs/shape_cropboard.ref 
ngl-test shape.py shape_cropboard_indices refs/shape_cropboard_indices.ref 
ngl-test shape.py shape_geometry_rtt_samples refs/shape_geometry_rtt_samples.ref 
ngl-test shape.py shape_triangle_msaa refs/shape_triangle_msaa.ref 
ngl-test text.py text_colors refs/text_colors.ref 
ngl-test text.py text_0_to_127 refs/text_0_to_127.ref 
ngl-test text.py text_align_cc refs/text_align_cc.ref 
ngl-test text.py text_align_cr refs/text_align_cr.ref 
ngl-test text.py text_align_cl refs/text_align_cl.ref 
ngl-test text.py text_align_bc refs/text_align_bc.ref 
ngl-test text.py text_align_br refs/text_align_br.ref 
ngl-test text.py text_align_bl refs/text_align_bl.ref 
ngl-test text.py text_align_tc refs/text_align_tc.ref 
ngl-test text.py text_align_tr refs/text_align_tr.ref 
ngl-test text.py text_align_tl refs/text_align_tl.ref 
ngl-test texture.py texture_3d refs/texture_3d.ref 
ngl-test texture.py texture_clear_and_scissor refs/texture_clear_and_scissor.ref 
ngl-test texture.py texture_cubemap refs/texture_cubemap.ref 
ngl-test texture.py texture_cubemap_from_mrt refs/texture_cubemap_from_mrt.ref 
ngl-test texture.py texture_data refs/texture_data.ref 
ngl-test texture.py texture_data_animated refs/texture_data_animated.ref 
ngl-test texture.py texture_data_unaligned_row refs/texture_data_unaligned_row.ref 
ngl-test texture.py texture_mipmap refs/texture_mipmap.ref 
ngl-test texture.py texture_scissor refs/texture_scissor.ref 
ngl-test texture.py texture_cubemap_from_mrt_msaa refs/texture_cubemap_from_mrt_msaa.ref 
ngl-test transform.py transform_animated_camera refs/transform_animated_camera.ref 
ngl-test transform.py transform_matrix refs/transform_matrix.ref 
ngl-test transform.py transform_translate refs/transform_translate.ref 
ngl-test transform.py transform_translate_animated refs/transform_translate_animated.ref 
ngl-test transform.py transform_scale refs/transform_scale.ref 
ngl-test transform.py transform_scale_animated refs/transform_scale_animated.ref 
ngl-test transform.py transform_scale_anchor refs/transform_scale_anchor.ref 
ngl-test transform.py transform_scale_anchor_animated refs/transform_scale_anchor_animated.ref 
ngl-test transform.py transform_rotate refs/transform_rotate.ref 
ngl-test transform.py transform_rotate_anchor refs/transform_rotate_anchor.ref 
ngl-test transform.py transform_rotate_quat refs/transform_rotate_quat.ref 
ngl-test transform.py transform_rotate_quat_anchor refs/transform_rotate_quat_anchor.ref 
ngl-test transform.py transform_rotate_quat_animated refs/transform_rotate_quat_animated.ref
