. scripts/env.sh
$PYSHELL $NGL_TEST data.py data_single_float_uniform refs/data_single_float_uniform.ref 
$PYSHELL $NGL_TEST data.py data_single_int_uniform refs/data_single_int_uniform.ref 
$PYSHELL $NGL_TEST data.py data_single_mat4_uniform refs/data_single_mat4_uniform.ref 
$PYSHELL $NGL_TEST data.py data_single_quat_mat4_uniform refs/data_single_quat_mat4_uniform.ref 
$PYSHELL $NGL_TEST data.py data_single_quat_vec4_uniform refs/data_single_quat_vec4_uniform.ref 
$PYSHELL $NGL_TEST data.py data_single_vec2_uniform refs/data_single_vec2_uniform.ref 
$PYSHELL $NGL_TEST data.py data_single_vec3_uniform refs/data_single_vec3_uniform.ref 
$PYSHELL $NGL_TEST data.py data_single_vec4_uniform refs/data_single_vec4_uniform.ref 
$PYSHELL $NGL_TEST data.py data_animated_quat_mat4_uniform refs/data_animated_quat_mat4_uniform.ref 
$PYSHELL $NGL_TEST data.py data_animated_quat_vec4_uniform refs/data_animated_quat_vec4_uniform.ref 
$PYSHELL $NGL_TEST data.py data_array_float_uniform refs/data_array_float_uniform.ref 
$PYSHELL $NGL_TEST data.py data_array_vec2_uniform refs/data_array_vec2_uniform.ref 
$PYSHELL $NGL_TEST data.py data_array_vec3_uniform refs/data_array_vec3_uniform.ref 
$PYSHELL $NGL_TEST data.py data_array_vec4_uniform refs/data_array_vec4_uniform.ref 
$PYSHELL $NGL_TEST data.py data_single_float_std140 refs/data_single_float_std140.ref 
$PYSHELL $NGL_TEST data.py data_single_int_std140 refs/data_single_int_std140.ref 
$PYSHELL $NGL_TEST data.py data_single_mat4_std140 refs/data_single_mat4_std140.ref 
$PYSHELL $NGL_TEST data.py data_single_quat_mat4_std140 refs/data_single_quat_mat4_std140.ref 
$PYSHELL $NGL_TEST data.py data_single_quat_vec4_std140 refs/data_single_quat_vec4_std140.ref 
$PYSHELL $NGL_TEST data.py data_single_vec2_std140 refs/data_single_vec2_std140.ref 
$PYSHELL $NGL_TEST data.py data_single_vec3_std140 refs/data_single_vec3_std140.ref 
$PYSHELL $NGL_TEST data.py data_single_vec4_std140 refs/data_single_vec4_std140.ref 
$PYSHELL $NGL_TEST data.py data_animated_quat_mat4_std140 refs/data_animated_quat_mat4_std140.ref 
$PYSHELL $NGL_TEST data.py data_animated_quat_vec4_std140 refs/data_animated_quat_vec4_std140.ref 
$PYSHELL $NGL_TEST data.py data_array_float_std140 refs/data_array_float_std140.ref 
$PYSHELL $NGL_TEST data.py data_array_vec2_std140 refs/data_array_vec2_std140.ref 
$PYSHELL $NGL_TEST data.py data_array_vec3_std140 refs/data_array_vec3_std140.ref 
$PYSHELL $NGL_TEST data.py data_array_vec4_std140 refs/data_array_vec4_std140.ref 
$PYSHELL $NGL_TEST data.py data_animated_buffer_float_std140 refs/data_animated_buffer_float_std140.ref 
$PYSHELL $NGL_TEST data.py data_animated_buffer_vec2_std140 refs/data_animated_buffer_vec2_std140.ref 
$PYSHELL $NGL_TEST data.py data_animated_buffer_vec3_std140 refs/data_animated_buffer_vec3_std140.ref 
$PYSHELL $NGL_TEST data.py data_animated_buffer_vec4_std140 refs/data_animated_buffer_vec4_std140.ref 
$PYSHELL $NGL_TEST data.py data_array_int_std140 refs/data_array_int_std140.ref 
$PYSHELL $NGL_TEST data.py data_array_ivec2_std140 refs/data_array_ivec2_std140.ref 
$PYSHELL $NGL_TEST data.py data_array_ivec3_std140 refs/data_array_ivec3_std140.ref 
$PYSHELL $NGL_TEST data.py data_array_ivec4_std140 refs/data_array_ivec4_std140.ref 
$PYSHELL $NGL_TEST data.py data_array_mat4_std140 refs/data_array_mat4_std140.ref 
$PYSHELL $NGL_TEST data.py data_single_float_std430 refs/data_single_float_std430.ref 
$PYSHELL $NGL_TEST data.py data_single_int_std430 refs/data_single_int_std430.ref 
$PYSHELL $NGL_TEST data.py data_single_mat4_std430 refs/data_single_mat4_std430.ref 
$PYSHELL $NGL_TEST data.py data_single_quat_mat4_std430 refs/data_single_quat_mat4_std430.ref 
$PYSHELL $NGL_TEST data.py data_single_quat_vec4_std430 refs/data_single_quat_vec4_std430.ref 
$PYSHELL $NGL_TEST data.py data_single_vec2_std430 refs/data_single_vec2_std430.ref 
$PYSHELL $NGL_TEST data.py data_single_vec3_std430 refs/data_single_vec3_std430.ref 
$PYSHELL $NGL_TEST data.py data_single_vec4_std430 refs/data_single_vec4_std430.ref 
$PYSHELL $NGL_TEST data.py data_animated_quat_mat4_std430 refs/data_animated_quat_mat4_std430.ref 
$PYSHELL $NGL_TEST data.py data_animated_quat_vec4_std430 refs/data_animated_quat_vec4_std430.ref 
$PYSHELL $NGL_TEST data.py data_array_float_std430 refs/data_array_float_std430.ref 
$PYSHELL $NGL_TEST data.py data_array_vec2_std430 refs/data_array_vec2_std430.ref 
$PYSHELL $NGL_TEST data.py data_array_vec3_std430 refs/data_array_vec3_std430.ref 
$PYSHELL $NGL_TEST data.py data_array_vec4_std430 refs/data_array_vec4_std430.ref 
$PYSHELL $NGL_TEST data.py data_animated_buffer_float_std430 refs/data_animated_buffer_float_std430.ref 
$PYSHELL $NGL_TEST data.py data_animated_buffer_vec2_std430 refs/data_animated_buffer_vec2_std430.ref 
$PYSHELL $NGL_TEST data.py data_animated_buffer_vec3_std430 refs/data_animated_buffer_vec3_std430.ref 
$PYSHELL $NGL_TEST data.py data_animated_buffer_vec4_std430 refs/data_animated_buffer_vec4_std430.ref 
$PYSHELL $NGL_TEST data.py data_array_int_std430 refs/data_array_int_std430.ref 
$PYSHELL $NGL_TEST data.py data_array_ivec2_std430 refs/data_array_ivec2_std430.ref 
$PYSHELL $NGL_TEST data.py data_array_ivec3_std430 refs/data_array_ivec3_std430.ref 
$PYSHELL $NGL_TEST data.py data_array_ivec4_std430 refs/data_array_ivec4_std430.ref 
$PYSHELL $NGL_TEST data.py data_array_mat4_std430 refs/data_array_mat4_std430.ref 
$PYSHELL $NGL_TEST data.py data_streamed_buffer_vec4 refs/data_streamed_buffer_vec4.ref 
$PYSHELL $NGL_TEST data.py data_streamed_buffer_vec4_time_anim refs/data_streamed_buffer_vec4_time_anim.ref 
