. scripts/env.sh
$PYSHELL $NGL_TEST live.py live_single_float_uniform refs/live_single_float_uniform.ref 
$PYSHELL $NGL_TEST live.py live_single_int_uniform refs/live_single_int_uniform.ref 
$PYSHELL $NGL_TEST live.py live_single_mat4_uniform refs/live_single_mat4_uniform.ref 
$PYSHELL $NGL_TEST live.py live_single_quat_mat4_uniform refs/live_single_quat_mat4_uniform.ref 
$PYSHELL $NGL_TEST live.py live_single_quat_vec4_uniform refs/live_single_quat_vec4_uniform.ref 
$PYSHELL $NGL_TEST live.py live_single_vec2_uniform refs/live_single_vec2_uniform.ref 
$PYSHELL $NGL_TEST live.py live_single_vec3_uniform refs/live_single_vec3_uniform.ref 
$PYSHELL $NGL_TEST live.py live_single_vec4_uniform refs/live_single_vec4_uniform.ref 
$PYSHELL $NGL_TEST live.py live_trf_single_mat4_uniform refs/live_trf_single_mat4_uniform.ref 
$PYSHELL $NGL_TEST live.py live_single_float_std140 refs/live_single_float_std140.ref 
$PYSHELL $NGL_TEST live.py live_single_int_std140 refs/live_single_int_std140.ref 
$PYSHELL $NGL_TEST live.py live_single_mat4_std140 refs/live_single_mat4_std140.ref 
$PYSHELL $NGL_TEST live.py live_single_quat_mat4_std140 refs/live_single_quat_mat4_std140.ref 
$PYSHELL $NGL_TEST live.py live_single_quat_vec4_std140 refs/live_single_quat_vec4_std140.ref 
$PYSHELL $NGL_TEST live.py live_single_vec2_std140 refs/live_single_vec2_std140.ref 
$PYSHELL $NGL_TEST live.py live_single_vec3_std140 refs/live_single_vec3_std140.ref 
$PYSHELL $NGL_TEST live.py live_single_vec4_std140 refs/live_single_vec4_std140.ref 
$PYSHELL $NGL_TEST live.py live_trf_single_mat4_std140 refs/live_trf_single_mat4_std140.ref 
$PYSHELL $NGL_TEST live.py live_single_float_std430 refs/live_single_float_std430.ref 
$PYSHELL $NGL_TEST live.py live_single_int_std430 refs/live_single_int_std430.ref 
$PYSHELL $NGL_TEST live.py live_single_mat4_std430 refs/live_single_mat4_std430.ref 
$PYSHELL $NGL_TEST live.py live_single_quat_mat4_std430 refs/live_single_quat_mat4_std430.ref 
$PYSHELL $NGL_TEST live.py live_single_quat_vec4_std430 refs/live_single_quat_vec4_std430.ref 
$PYSHELL $NGL_TEST live.py live_single_vec2_std430 refs/live_single_vec2_std430.ref 
$PYSHELL $NGL_TEST live.py live_single_vec3_std430 refs/live_single_vec3_std430.ref 
$PYSHELL $NGL_TEST live.py live_single_vec4_std430 refs/live_single_vec4_std430.ref 
$PYSHELL $NGL_TEST live.py live_trf_single_mat4_std430 refs/live_trf_single_mat4_std430.ref 
